(async () => {
    // adds support for requiring modules with their original path

    let wreq = webpackChunkdiscord_app.push([[Symbol()], {}, (r) => r]);
    webpackChunkdiscord_app.pop();

    const readJSONL = (text) => {
        return text
            .split('\n')
            .map((line) => line.trim())
            .filter(Boolean)
            .map(JSON.parse);
    };

    const compileFindWith = (findWith) => {
        if (Array.isArray(findWith)) return findWith.map(compileFindWith);
        if (typeof findWith === 'string') return findWith;
        if (typeof findWith === 'object' && findWith?.type === 'regexp')
            return new RegExp(findWith.value, findWith.flags);
        return findWith;
    };

    const test = (pattern, content) => {
        let isMatch = false;
        if (pattern instanceof RegExp)
            isMatch = new RegExp(
                pattern.source.replace(/\\w/g, '[a-zA-Z0-9$_]+'),
                pattern.flags,
            ).test(content);
        if (typeof pattern === 'string') isMatch = content.includes(pattern);
        if (Array.isArray(pattern))
            isMatch = pattern.every((p) => test(p, content));

        return isMatch;
    };

    window.cached_mappings ??= {};
    // to avoid rechecking
    window.checked_modules ??= new Set();

    const getPaths = async (id, content, exports) => {
        const paths = [];
        for (let item of [...autogenerated_mappings, ...mappings]) {
            if (test(item.find_with, content)) paths.push(...item.paths);
            if (item.id === id + '.js') paths.push(...item.paths);
        }

        if (paths.length === 0) window.checked_modules.add(id);
        return paths;
    };

    const base =
        'https://raw.githubusercontent.com/wavedevgit/discord-mappings-project/refs/heads/main';

    const autogenerated_mappings = (
        await Promise.all(
            ['assets', 'experiments', 'intl', 'stores']
                .map(
                    (category) =>
                        `/mappings/autogenerated/paths_${category}.jsonl`,
                )
                .map((path) => fetch(base.concat(path)).then((x) => x.text())),
        )
    )
        .map(readJSONL)
        .flat();

    const mappings = await (
        await fetch(
            'https://raw.githubusercontent.com/wavedevgit/discord-mappings-project/refs/heads/main/mappings/paths.compiled.json',
        )
    ).json();

    for (const moduleId in wreq.m) {
        if (window.checked_modules.has(moduleId)) continue;
        try {
            const [content, exports] = [
                wreq.m[moduleId].toString(),
                wreq(moduleId),
            ];
            const paths = await getPaths(moduleId, content, exports);
            for (const path of paths) window.cached_mappings[path] = moduleId;
            if (paths.length) console.log(moduleId, paths);
        } catch {}
    }

    window.RequireWithMapping = (id) => {
        if (!window.cached_mappings[id] && !window.checked_modules.has(id)) {
            try {
                getPaths(id, wreq.m[id].toString(), wreq(id)).then((paths) => {
                    for (const path of paths)
                        window.cached_mappings[path] = moduleId;
                });
            } catch {}
        }
        return wreq(window.cached_mappings[id] || id);
    };
})();
