import fs from 'fs/promises';
import pathsDone from '../mappings/paths.js';

const androidsrc = JSON.parse(
    await fs.readFile('./data/files/src_names_android.json', 'utf-8'),
);

const readJSONL = async (p) => {
    const text = await fs.readFile(p, 'utf8');

    return text
        .split('\n')
        .map((line) => line.trim())
        .filter(Boolean)
        .map(JSON.parse);
};
const autogenerated = (
    await Promise.all(
        autogeneratedPaths.map((filename) =>
            readJSONL(path.join(AUTOGENERATED_BASE, filename)),
        ),
    )
).flat();
const manuallydone = pathsDone.map((e) => e.paths).flat();

await fs.writeFile(
    './data/done.txt',
    androidsrc
        .filter(
            (e) =>
                autogenerated.includes(e.file) || manuallydone.includes(e.file),
        )
        .map((e) => e.file)
        .join('\n'),
);

await fs.writeFile(
    './data/left.txt',
    androidsrc
        .filter(
            (e) =>
                !autogenerated.includes(e.file) &&
                !manuallydone.includes(e.file),
        )
        .map((e) => e.file)
        .join('\n'),
);
