import fs from 'fs/promises';
import path from 'path';

const readJSON = (p) => fs.readFile(p, 'utf-8').then(JSON.parse);
const writeJSONL = async (p, arr) => {
    const fh = await fs.open(p, 'w');
    for (const e of arr) await fh.write(JSON.stringify(e) + '\n');
    await fh.close();
};
const [client, ios, android, androidsrc, experimentsandroid] =
    await Promise.all([
        readJSON('./data/files/client_hashes.json'),
        readJSON('./data/files/assets_ios.json'),
        readJSON('./data/files/assets_android.json'),
        readJSON('./data/files/src_names_android.json'),
        readJSON('./data/files/experiments_android.json'),
    ]);

const getHashByEtag = (etag) => etag.match(/[a-fA-F0-9]+/)?.[0] || '';

const assets = [];
const intl = [];

for (let file of client) {
    const hash = getHashByEtag(file?.etag || '');
    const matches = [ios, android]
        .map((src) =>
            src.filter(
                (e) =>
                    e?.etag === file.etag ||
                    getHashByEtag(e?.etag || '') === hash ||
                    e.hash === hash ||
                    (e?.hash === file?.hash && e?.hash && file?.hash),
            ),
        )
        .flat();

    if (matches.length > 0 && !file.raw)
        assets.push({
            find_with: file?.url?.split?.('/')?.pop?.(),
            paths: matches.map((e) => e.path),
            hash,
            etag: file.etag,
        });

    if (file?.raw) {
        const paths = [ios, android]
            .map((src) => src.filter((p) => p?.hash == file?.hash))
            .flat()
            .map((e) => e.path);
        if (paths.length > 0)
            intl.push({
                id: file.raw,
                hash: file.hash,
                paths,
            });
    }
}

const stores = androidsrc
    .filter((f) => path.basename(f.file).endsWith('Store.tsx'))
    .map((f) => ({
        find_with: {
            type: 'regexp',
            flags: '',
            value: new RegExp(
                `static\\s+displayName\\s*=\\s*["']${path
                    .basename(f.file)
                    .replace('.tsx', '')}["']`,
            ).source,
        },
        paths: [f.file],
    }));

const experiments = experimentsandroid
    .filter((e) => e.kind && e.id)
    .map((e) => ({
        find_with: [e.kind, e.id, e.keyRequired],
        paths: [e.path],
    }));

await Promise.all([
    writeJSONL('./mappings/autogenerated/paths_assets.jsonl', assets),
    writeJSONL('./mappings/autogenerated/paths_intl.jsonl', intl),
    writeJSONL('./mappings/autogenerated/paths_stores.jsonl', stores),
    writeJSONL('./mappings/autogenerated/paths_experiments.jsonl', experiments),
]);
