import fs from 'fs/promises';

const androidsrc = JSON.parse(
    await fs.readFile('./data/files/src_names_android.json', 'utf-8'),
);

const autogenerated = JSON.parse(
    await fs.readFile('./mappings/autogenerated/paths.json', 'utf-8'),
)
    .map((e) => e.paths)
    .flat();
const manuallydone = JSON.parse(
    await fs.readFile('./mappings/paths.json', 'utf-8'),
)
    .map((e) => e.paths)
    .flat();

await fs.writeFile(
    './data/done.txt',
    androidsrc
        .filter(
            (e) =>
                autogenerated.includes(e.file) || manuallydone.includes(e.file),
        )
        .map((e) => e.file)
        .join('\n'),
);

await fs.writeFile(
    './data/left.txt',
    androidsrc
        .filter(
            (e) =>
                !autogenerated.includes(e.file) &&
                !manuallydone.includes(e.file),
        )
        .map((e) => e.file)
        .join('\n'),
);
