import fs from 'fs/promises';
import path from 'path';

const client = JSON.parse(
    await fs.readFile('./data/files/client_hashes.json', 'utf-8'),
);
const ios = JSON.parse(
    await fs.readFile('./data/files/assets_ios.json', 'utf-8'),
);
const android = JSON.parse(
    await fs.readFile('./data/files/assets_android.json', 'utf-8'),
);
const androidsrc = JSON.parse(
    await fs.readFile('./data/files/src_names_android.json', 'utf-8'),
);

const result = [];

for (let file of client) {
    const getHasheByEtag = (etag) => etag.match(/[a-fA-F0-9]+/)?.[0] || '';
    const hash = getHasheByEtag(file.etag);

    const paths = [
        ios.filter(
            (e) =>
                e?.etag === file.etag ||
                getHasheByEtag(e?.etag || '') === hash ||
                e.hash === hash,
        ),
        android.filter(
            (e) =>
                e?.etag === file.etag ||
                getHasheByEtag(e?.etag || '') === hash ||
                e.hash === hash,
        ),
    ];

    if (paths.flat().length > 0)
        result.push({
            find_with: file.url.split('/').pop(),
            paths: paths.flat().map((e) => e.path),
            hash: hash,
            etag: file.etag,
        });
}

for (let file of androidsrc) {
    const fileName = path.basename(file.file);
    if (fileName.endsWith('Store.tsx')) console.log(fileName);
    if (fileName.endsWith('Store.tsx'))
        result.push({
            find_with: `static displayName = "${fileName.replace('.tsx', '')}"`,
            paths: [file.file],
        });
}

await fs.writeFile(
    './mappings/autogenerated/paths.json',
    JSON.stringify(result, null, 4),
    'utf-8',
);
