import fs from 'fs/promises';
import path from 'path';
import paths from '../mappings/paths.js';

const readJSONL = async (p) => {
    const text = await fs.readFile(p, 'utf8');

    return text
        .split('\n')
        .map((line) => line.trim())
        .filter(Boolean)
        .map(JSON.parse);
};
const writeJSONL = async (p, arr) => {
    const fh = await fs.open(p, 'w');
    for (const e of arr) await fh.write(JSON.stringify(e) + '\n');
    await fh.close();
};

const AUTOGENERATED_BASE = './mappings/autogenerated/';
const autogeneratedPaths = await fs.readdir(AUTOGENERATED_BASE);

const autogenerated = (
    await Promise.all(
        autogeneratedPaths.map((filename) =>
            readJSONL(path.join(AUTOGENERATED_BASE, filename)),
        ),
    )
).flat();

const base = './discrapper-canary';
const chunksFolder = path.join(base, 'chunks');

const chunks = await fs.readdir(chunksFolder);
const result = [];

const test = (pattern, content) => {
    let isMatch = false;
    if (pattern instanceof RegExp)
        isMatch = new RegExp(
            pattern.source.replace(/\\w/g, '[a-zA-Z0-9$_]+'),
            pattern.flags,
        ).test(content);
    if (typeof pattern === 'string') isMatch = content.includes(pattern);
    if (pattern?.type === 'regexp')
        isMatch = new RegExp(
            pattern.value.replace(/\\w/g, '[a-zA-Z0-9$_]+'),
            pattern.flags || '',
        ).test(content);
    if (Array.isArray(pattern))
        isMatch = pattern.every((p) => test(p, content));

    return isMatch;
};

for (const chunk of chunks) {
    const content = await fs.readFile(path.join(chunksFolder, chunk), 'utf-8');
    for (const item of [...autogenerated, ...paths]) {
        if (item?.id && item.id === chunk) {
            result.push({
                id: chunk,
                paths: item.paths.map((p) => p.replace('app/', 'discord_app/')),
            });
            continue;
        }
        if (test(item.find_with, content)) {
            result.push({
                id: chunk,
                paths: item.paths.map((p) => p.replace('app/', 'discord_app/')),
            });
            continue;
        }
    }
}

await writeJSONL('./output/result.jsonl', result);
