name: Generate Mappings

on:
    workflow_dispatch:

    schedule:
        - cron: '*/5 * * * *'

permissions:
    contents: write

jobs:
    generate:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 26.3.0

            - name: Install dependencies
              run: npm i

            - name: Generate mappings
              run: bash gen_mappings.sh

            - name: Commit changes
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

                  git add .

                  if git diff --cached --quiet; then
                    echo "No changes to commit"
                    exit 0
                  fi

                  git commit -m "chore: update mappings"
                  git push
